MOCK_DATA = [{
    "symbol": "GE",
    "companyName": "General Electric Company",
    "exchange": "New York Stock Exchange",
    "industry": "Industrial Products",
    "website": "http://www.ge.com",
    "description": "General Electric Co is a digital industrial company. It operates in various segments, including power and water, oil and gas, energy management, aviation, healthcare, transportation, appliances and lighting, and more.",
    "CEO": "John L. Flannery",
    "issueType": "cs",
    "sector": "Industrials"
},
    {
    "symbol": "LE",
    "companyName": "General Electric Company",
    "exchange": "New York Stock Exchange",
    "industry": "Industrial Products",
    "website": "http://www.ge.com",
    "description": "General Electric Co is a digital industrial company. It operates in various segments, including power and water, oil and gas, energy management, aviation, healthcare, transportation, appliances and lighting, and more.",
    "CEO": "John L. Flannery",
    "issueType": "cs",
    "sector": "Industrials"
},
    {
    "symbol": "LE",
    "companyName": "General Electric Company",
    "exchange": "New York Stock Exchange",
    "industry": "Industrial Products",
    "website": "http://www.ge.com",
    "description": "General Electric Co is a digital industrial company. It operates in various segments, including power and water, oil and gas, energy management, aviation, healthcare, transportation, appliances and lighting, and more.",
    "CEO": "John L. Flannery",
    "issueType": "cs",
    "sector": "Industrials"
},
    {
    "symbol": "LE",
    "companyName": "General Electric Company",
    "exchange": "New York Stock Exchange",
    "industry": "Industrial Products",
    "website": "http://www.ge.com",
    "description": "General Electric Co is a digital industrial company. It operates in various segments, including power and water, oil and gas, energy management, aviation, healthcare, transportation, appliances and lighting, and more.",
    "CEO": "John L. Flannery",
    "issueType": "cs",
    "sector": "Industrials"
},
    {
    "symbol": "LE",
    "companyName": "General Electric Company",
    "exchange": "New York Stock Exchange",
    "industry": "Industrial Products",
    "website": "http://www.ge.com",
    "description": "General Electric Co is a digital industrial company. It operates in various segments, including power and water, oil and gas, energy management, aviation, healthcare, transportation, appliances and lighting, and more.",
    "CEO": "John L. Flannery",
    "issueType": "cs",
    "sector": "Industrials"
},
    {
    "symbol": "LE",
    "companyName": "General Electric Company",
    "exchange": "New York Stock Exchange",
    "industry": "Industrial Products",
    "website": "http://www.ge.com",
    "description": "General Electric Co is a digital industrial company. It operates in various segments, including power and water, oil and gas, energy management, aviation, healthcare, transportation, appliances and lighting, and more.",
    "CEO": "John L. Flannery",
    "issueType": "cs",
    "sector": "Industrials"
},
    {
    "symbol": "LE",
    "companyName": "General Electric Company",
    "exchange": "New York Stock Exchange",
    "industry": "Industrial Products",
    "website": "http://www.ge.com",
    "description": "General Electric Co is a digital industrial company. It operates in various segments, including power and water, oil and gas, energy management, aviation, healthcare, transportation, appliances and lighting, and more.",
    "CEO": "John L. Flannery",
    "issueType": "cs",
    "sector": "Industrials"
},
    {
    "symbol": "LE",
    "companyName": "General Electric Company",
    "exchange": "New York Stock Exchange",
    "industry": "Industrial Products",
    "website": "http://www.ge.com",
    "description": "General Electric Co is a digital industrial company. It operates in various segments, including power and water, oil and gas, energy management, aviation, healthcare, transportation, appliances and lighting, and more.",
    "CEO": "John L. Flannery",
    "issueType": "cs",
    "sector": "Industrials"
},
    {
    "symbol": "LE",
    "companyName": "General Electric Company",
    "exchange": "New York Stock Exchange",
    "industry": "Industrial Products",
    "website": "http://www.ge.com",
    "description": "General Electric Co is a digital industrial company. It operates in various segments, including power and water, oil and gas, energy management, aviation, healthcare, transportation, appliances and lighting, and more.",
    "CEO": "John L. Flannery",
    "issueType": "cs",
    "sector": "Industrials"
},
    {
    "symbol": "LE",
    "companyName": "General Electric Company",
    "exchange": "New York Stock Exchange",
    "industry": "Industrial Products",
    "website": "http://www.ge.com",
    "description": "General Electric Co is a digital industrial company. It operates in various segments, including power and water, oil and gas, energy management, aviation, healthcare, transportation, appliances and lighting, and more.",
    "CEO": "John L. Flannery",
    "issueType": "cs",
    "sector": "Industrials"
}]
